import java.util.HashMap;

public class KeyboardMap {

	private static HashMap<Integer,String> map = new HashMap<Integer,String>();
	
	private static void init() {
		// Generated by: 
		// System.out.println("map.put("+e.getRawCode()+", \""+NativeKeyEvent.getKeyText(e.getKeyCode())+"\");" );
		// For typing in Eclipse Console:
		// System.out.print("\";\nraw["+tempCounter+"] = "+e.getRawCode()+";\nkey["+(tempCounter+1)+"] = \"");
		
		map.put(8, "Rücktaste");
		map.put(9, "Tabulator");
		map.put(13, "Enter");
		map.put(19, "Pause");
		map.put(20, "Feststelltaste");
		map.put(27, "ESC");
		map.put(32, "Leertaste");
		map.put(33, "Bild auf");
		map.put(34, "Bild ab");
		map.put(35, "Ende");
		map.put(36, "Pos 1");
		map.put(37, "Links");
		map.put(38, "Oben");
		map.put(39, "Rechts");
		map.put(40, "Unten");
		map.put(44, "Druck");
		map.put(45, "Einfg");
		map.put(46, "Entf");
		map.put(48, "0");
		map.put(49, "1");
		map.put(50, "2");
		map.put(51, "3");
		map.put(52, "4");
		map.put(53, "5");
		map.put(54, "6");
		map.put(55, "7");
		map.put(56, "8");
		map.put(57, "9");
		map.put(65, "a");
		map.put(66, "b");
		map.put(67, "c");
		map.put(68, "d");
		map.put(69, "e");
		map.put(70, "f");
		map.put(71, "g");
		map.put(72, "h");
		map.put(73, "i");
		map.put(74, "j");
		map.put(75, "k");
		map.put(76, "l");
		map.put(77, "m");
		map.put(78, "n");
		map.put(79, "o");
		map.put(80, "p");
		map.put(81, "q");
		map.put(82, "r");
		map.put(83, "s");
		map.put(84, "t");
		map.put(85, "u");
		map.put(86, "v");
		map.put(87, "w");
		map.put(88, "x");
		map.put(89, "y");
		map.put(90, "z");
		map.put(91, "Windows Links");
		map.put(92, "Windows Links");
		map.put(93, "Kontextmenü");
		map.put(96, "Num 0");
		map.put(97, "Num 1");
		map.put(98, "Num 2");
		map.put(99, "Num 3");
		map.put(100, "Num 4");
		map.put(101, "Num 5");
		map.put(102, "Num 6");
		map.put(103, "Num 7");
		map.put(104, "Num 8");
		map.put(105, "Num 9");
		map.put(106, "Num *");
		map.put(107, "Num +");
		map.put(109, "Num -");
		map.put(110, "Num ,");
		map.put(111, "Num /");
		map.put(112, "F1");
		map.put(113, "F2");
		map.put(114, "F3");
		map.put(115, "F4");
		map.put(116, "F5");
		map.put(117, "F6");
		map.put(118, "F7");
		map.put(119, "F8");
		map.put(120, "F9");
		map.put(121, "F10");
		map.put(122, "F11");
		map.put(123, "F12");
		map.put(144, "Num");
		map.put(145, "Rollen");
		map.put(160, "Shift links");
		map.put(161, "Shift rechts");
		map.put(162, "Strg");
		map.put(163, "Strg rechts");
		map.put(164, "Alt");
		map.put(165, "Alt");
		map.put(186, "ü");
		map.put(187, "+");
		map.put(188, ",");
		map.put(189, "-");
		map.put(190, ".");
		map.put(191, "#");
		map.put(192, "ö");
		map.put(219, "ß");
		map.put(220, "^");
		map.put(221, "´");
		map.put(222, "ä");
		map.put(226, "<");

	}
	
	
	public static String getKey(int key) {
		if(map.size() == 0) {
			init();
		}
		String result = map.get(key);
		if(result == null) {
			result = "Unbekannt: "+key;
			
		}
		return result;
	}
	
}
